{"uuid": "7cc0537e-62e5-4360-afff-869387a9a2fc", "children": ["afbdbf16-e3fa-4f1f-80a1-5cd2d0f61690"], "befores": [{"name": "web_buy_goods", "status": "passed", "start": 1603160564643, "stop": 1603160636495}], "afters": [{"name": "web_buy_goods::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=85.0.4183.83)\n\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 181, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 791, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Pycharm_workspace\\Hobay\\TestCases\\Web\\conftest.py\", line 69, in web_buy_goods\n    driver.refresh()\n  File \"D:\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 831, in refresh\n    self.execute(Command.REFRESH)\n  File \"D:\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1603160637168, "stop": 1603160637204}], "start": 1603160564643, "stop": 1603160637204}